# KNN

When there are multiple categories of data, we often face the problem of classifying newly added data. For example, we may classify wines based on taste and color, categorize newly released movies according to their content and format, or perform facial recognition based on previously observed facial features. These types of problems can be solved using the very classic K-Nearest Neighbors (KNN) algorithm in machine learning.

## 1. The Principle and Code Implementation of the KNN

### 1.1 Principle of KNN

The basic principle of the KNN algorithm is simple: for a new sample, the goal of the K-Nearest Neighbors algorithm is to find the K most similar data points to it in the existing data, or in other words, the K data points "closest to it". If most of these K data points belong to a certain category, then the sample also belongs to that category.

So how do we understand this **"closest to it"**? For example, I have two shapes, a triangle and a square. Suppose I have a new sample, K = 3, then we find the three closest data points around this new sample. We find one triangle and two squares. According to the principle of "majority rule", we consider this new sample to belong to the square category. This closestness can be determined by similarity or distance.

The most common distance is the Euclidean distance. Suppose we have two samples A and B, $A(X_1,Y_1)$ and $B(X_2,Y_2)$, the distance formula is:

$$|AB|=\sqrt{(X_1-X_2)^2+(Y_1-Y_2)^2}$$

### 1.2 The calculation steps of KNN

#### 1. Data samples

In [ ]:
import pandas as pd
df = pd.DataFrame({'Alcohol content (%)':[5, 6, 4, 8, 10],
                   'Malic acid content (%)':[2, 1, 1, 3, 2],
                   'Classification':[0, 0, 0, 1, 1]})
df

   Alcohol content (%)  Malic acid content (%)  Classification
0                    5                       2               0
1                    6                       1               0
2                    4                       1               0
3                    8                       3               1
4                   10                       2               1

This example is about "how to determine the type of wine," where a "classification" value of 0 represents wine A, and a value of 1 represents wine B. Now, there is a new sample with an "alcohol content" of 7, a "malic acid content" of 1, and an unknown "classification."

#### 2. Calculate distance using the distance formula.

In [2]:
df['Distance from new sample'] = [2.24, 1, 3, 2.24, 3.16]
df

,Alcohol content (%),Malic acid content (%),Classification,Distance from new sample
0,5,2,0,2.24
1,6,1,0,1.00
2,4,1,0,3.00
3,8,3,1,2.24
4,10,2,1,3.16

#### 3. Determining the class Based on the K Value

If we set K=1, meaning the category of the original sample closest to the new sample is taken as the category of the new sample, then in this case, the category with a distance of 1 from the new sample is selected, which is 0, wine A. If K=3, it is still 0, wine A.

Note: When calculating the distance here, because the dimensions of different feature variables are not much different, if the "alcohol content" is malated to 10 times its original value while the "malic acid content" remains unchanged, then the dimensions of the two will be significantly different. If the distance is calculated directly in this case, the importance of "alcohol content" in the model will far exceed that of "malic acid content," thus losing the role of "malic acid content" as a feature variable, and the result will also have a relatively large error.

#### Therefore, if the scales of different characteristic variables differ significantly and they influence each other during modeling, we usually preprocess the data, typically using data standardization or data normalization.

### 1.3 Code implementation of KNN

In [4]:
import pandas as pd 
df = pd.read_excel('Wine classification.xlsx')
x_train = df[['Alcohol content (%)','Malic acid content (%)']]
y_train = df['Classification']

In [8]:
from sklearn.neighbors import KNeighborsClassifier as KNN

knn = KNN(n_neighbors=3)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [9]:
x_test = [[7, 1], [8, 3]]
answer = knn.predict(x_test)
answer

/opt/miniconda3/envs/research/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([0, 1])

## 2. KNN application: Handwritten Digit Recognition Model

### 2.1 Background

Image recognition is a very important application scenario in the field of machine learning. Face recognition is based on machine learning-related image recognition algorithms. This simple case study is a handwritten digit recognition model, whose principles share similarities with face recognition.

### 2.2 The principle of handwritten digit recognition

Handwritten digit recognition, or image recognition, essentially converts images into a numerical form that computers can process. For example, the number 4.

1. Image Binarization: We can convert the image-formatted number 4 into a "new number 4" composed of 0s and 1s. We can use 1s to represent colored areas and 0s to represent uncolored areas. This completes the first step of handwritten digit recognition: converting the image into computer-recognizable content—the numbers 0 and 1.

2. Two-Dimensional Array to One-Dimensional Array: Because the image above directly uses 1s to represent colored areas and 0s to represent uncolored areas, it's like filling a large matrix with 1s and 0s. To facilitate machine learning modeling, we need to perform a simple processing on the two-dimensional array: concatenating all the numbers after the first row of numbers. For example, if my 01 matrix is ​​32 by 32, then the final result is 1 by 1024.

3. Distance Calculation: The result above shows a row vector. The Euclidean distance between the corresponding row vectors of two images reflects the similarity between the two images. Therefore, we can use the K-nearest neighbors algorithm to calculate the Euclidean distance between the new sample and each sample in the original training set, select the K nearest neighbors of the new sample, and use the classification of the majority of nearest neighbors as the classification of the new sample. The calculation formula is simply the Euclidean distance formula, where the values ​​are 0 and 1.

### 2.3 Code implementation

In [10]:
# Read the data: The first column, "Corresponding Number," represents the target variable y, and the numbers 0-1023 represent the binarized feature variables x, totaling 1934 data points.
import pandas as pd
df = pd.read_excel('Handwritten font recognition.xlsx')
df.head()

,Corresponding Number,0,1,2,3,4,5,6,7,8,...,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
# 1. Read the data: The first column, "Corresponding Number," represents the target variable y, and the numbers 0-1023 represent the binarized feature variables x, totaling 1934 data points.
import pandas as pd
df = pd.read_excel('Handwritten font recognition.xlsx')

# 2. Extract feature variables and target variables: Since all numbers consist of 0 and 1, standardization is not necessary.
x = df.drop(columns='Corresponding Number')
y = df['Corresponding Number']

# If standardization is needed:
# from sklearn.preprocessing import StandardScaler
# x = StandardScaler().fit_transform(x)

# 3.Divide into training and test sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)

# 4. Set up prediction model
from sklearn.neighbors import KNeighborsClassifier as KNN
knn = KNN(n_neighbors=5)
knn.fit(x_train, y_train)

# 5. Prediction and performance assessment
y_pred = knn.predict(x_test)

a = pd.DataFrame()
a['Prediction value'] = list(y_pred)
a['Actual value'] = list(y_test)

# Accuracy is pretty high
from sklearn.metrics import accuracy_score
score = accuracy_score(y_pred, y_test)
score

0.9819121447028424

In [12]:
# Get the model score; this is the model's built-in scoring function, and it works the same as above.
score = knn.score(x_test, y_test)
score

0.9819121447028424

In [13]:
# Here, we can replace the n_neighbors parameter with other values ​​for parameter tuning.
# Use cross-validation and grid search
from sklearn.model_selection import GridSearchCV
parameters = {'n_neighbors':[1, 2, 3, 4, 5, 6, 7, 8]}

knn = KNN()
grid_search = GridSearchCV(knn, parameters, cv=5) # 5-fold cross validation

grid_search.fit(x_train, y_train)        # Performing a grid search based on accuracy to find the optimal values ​​for the parameters.
grid_search.best_params_['n_neighbors']  # Obtain the optimal n_neighbors

1

## 3.Image recognition principle

Computers cannot directly recognize an image. We can use preprocessing techniques to convert the image into content that computers can recognize, such as the numbers 0 and 1.

### 3.1 Image Resizing and Display

The Pillow library is used here.

In [ ]:
from PIL import Image
img = Image.open('Digit 4.png')   # Open Digit 4.png
img = img.resize((32, 32))      # This is for adjusting the image size to 32*32 pixels.
img.show()
# This will display the original image 4.

### 3.2 Image Grayscale Processing

The original number 4 is red. We need to process it into grayscale, converting it to a black and white number 4 so that it can be converted into the numbers 0 and 1 later.

In [ ]:
img = img.convert('L')  # Grayscale processing
img.show()

### 3.3 Image binarization

After obtaining the black and white digit 4, image binarization can be performed.

In [16]:
import numpy as np
# lambda is an anonymous function that assigns a value of 0 to pixels with a color value greater than 128, and 1 to pixels with a color value less than 128.
# Because after grayscale processing, each pixel is represented by a number ranging from 0 to 255, where 0 represents black and 255 represents white.
# Using 128 as the dividing line, previously, lighter colors were assigned a value of 0, and darker colors were assigned a value of 1.
img_new = img.point(lambda x: 0 if x > 128 else 1)   
arr = np.array(img_new)

In [7]:
arr.shape

(32, 32)

In [17]:
for i in range(arr.shape[0]):
    print(arr[i])
# The digit 4, composed of 0 and 1, are printed.

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

### 3.4 Convert a two-dimensional array to a one-dimensional array

In [18]:
arr_new = arr.reshape(1, -1)
arr_new.shape

(1, 1024)

In [19]:
# Now you can import it into the model.
# 1. Read the data: The first column, "Corresponding Number," represents the target variable y, and the numbers 0-1023 represent the binarized feature variables x, totaling 1934 data points.
import pandas as pd
df = pd.read_excel('Handwritten font recognition.xlsx')

# 2. Extract feature variables and target variables: Since all numbers consist of 0s and 1s, standardization is not necessary.
x = df.drop(columns='Corresponding Number')
y = df['Corresponding Number']

# If standarization is needed:
# from sklearn.preprocessing import StandardScaler
# x = StandardScaler().fit_transform(x)

# 3. Divide the dataset into training and testing sets.
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)

# 4. Set up prediction model
from sklearn.neighbors import KNeighborsClassifier as KNN
knn = KNN(n_neighbors=5)
knn.fit(x_train, y_train)

# 5. Prediction and performance assessment
y_pred = knn.predict(x_test)

a = pd.DataFrame()
a['Prediction value'] = list(y_pred)
a['Actual value'] = list(y_test)


from sklearn.metrics import accuracy_score
score = accuracy_score(y_pred, y_test)
score

0.9819121447028424

In [21]:
answer = knn.predict(arr_new)
print('The digit in the picture is: '+ str(answer[0]))

The digit in the picture is: 4

In [22]:
answer

array([4])

In [23]:

import pandas as pd
df = pd.read_excel('Handwritten font recognition.xlsx')

x = df.drop(columns='Corresponding Number')
y = df['Corresponding Number']


from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)


from sklearn.neighbors import KNeighborsClassifier as KNN
knn = KNN(n_neighbors=5)
knn.fit(x_train, y_train)

# Image processing
# (1) Image reading, resizing and grayscale processing
from PIL import Image
img = Image.open('new digit.png')
img = img.resize((32, 32))
img = img.convert('L')

# (2) Image binarization and conversion of two-dimensional arrays to one-dimensional arrays
import numpy as np
img_new = img.point(lambda x: 0 if x > 128 else 1)   
arr = np.array(img_new)          
arr_new = arr.reshape(1, -1)

# (3) Make predictions
answer = knn.predict(arr_new)
print('The digit in the picture is: '+str(answer[0]))

The digit in the picture is: 1

In summary, the K-nearest neighbors algorithm is a classic machine learning algorithm with a clear and simple principle that is easy to understand. However, it also has drawbacks, such as high computational cost and slow fitting speed when the sample size is large.